spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.94.90.134:3306/share?userSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 10000
      connection-test-query: SELECT 1
  redis:
    port: 6379
    password:
    host: 47.94.90.134
    database: 0
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-wait: -1
        max-active: 8
  security:
    user:
      name: root
      password: root
server:
  port: 10086